name: wordify-webapp
version: "0.0.0"

dependencies:
  - base >=4.9.1.0 && <5
  - yesod >=1.6 && <1.7
  - yesod-core >=1.6 && <1.7
  - yesod-auth >=1.6 && <1.7
  - yesod-static >=1.6 && <1.7
  - yesod-form >=1.7.9 && <1.8.0
  - yesod-auth-oauth2 >= 0.7.4.0 && < 0.8.0.0
  - classy-prelude >=1.5 && <1.6
  - classy-prelude-conduit >=1.5 && <1.6
  - classy-prelude-yesod >=1.5 && <1.6
  - bytestring >=0.12.1.0 && <0.13.0.0
  - text >= 2.1.1 && <2.2.0
  - persistent >=2.14.6.3 && <2.18.0.0
  - persistent-sqlite >=2.13.3.0 && < 2.14.0.0
  - persistent-template >=2.12.0.0 && <2.13.0.0
  - template-haskell
  - shakespeare >=2.1.1 && <2.2.0
  - hjsmin >=0.1 && <0.3
  - monad-control >=0.3 && <1.1
  - wai-extra >=3.1.16 && <3.2.0
  - yaml >=0.11 && <0.12
  - http-client-tls >=0.3 && <0.4
  - http-conduit >=2.3 && <2.4
  - directory >=1.1 && <1.4
  - warp >=3.4.7 && <3.5.0
  - data-default
  - aeson >=2.2.3.0 && <2.3.0.0
  - conduit >=1.0 && <2.0
  - monad-logger >=0.3 && <0.4
  - fast-logger >=3.2.5 && <3.3.0
  - wai-logger >=2.5.0 && <2.6.0
  - file-embed
  - safe
  - unordered-containers
  - containers
  - vector
  - time
  - case-insensitive
  - wai
  - foreign-store
  - websockets
  - file-embed
  - safe
  - listsafe
  - unordered-containers
  - containers
  - vector
  - time
  - suspend
  - timers
  - split
  - filepath
  - semigroups
  - transformers
  - conduit-combinators
  - mime-mail
  - random
  - cookie
  - errors
  - stm
  - monad-loops >= 0.4.3 && < 0.5
  - resource-pool
  - resourcet
  - mtl
  - wordify
  - yesod-websockets
  - random-shuffle
  - uri-bytestring
  - esqueleto
  - splitmix
  - stm-containers
  - foldl
  - deferred-folds
  - req
  - async
  - base16-bytestring
  - tagsoup
  - base64-bytestring
  - http-client
  - http-types
  - lens
  - web-push

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
  when:
    - condition: (flag(dev)) || (flag(library-only))
      then:
        ghc-options:
          - -Wall
          - -fwarn-tabs
          - -O0
        cpp-options: -DDEVELOPMENT
      else:
        ghc-options:
          - -Wall
          - -fwarn-tabs
          - -O2

# Runnable executable for our application
executables:
  wordify-webapp:
    main: main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - wordify-webapp
    when:
      - condition: flag(library-only)
        buildable: false

# Test suite
tests:
  wordify-webapp-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
      - wordify-webapp
      - hspec >=2.0.0
      - yesod-test
      - microlens

# Define flags used by "yesod devel" to make compilation faster
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false

default-extensions: TemplateHaskell
  QuasiQuotes
  OverloadedStrings
  NoImplicitPrelude
  CPP
  MultiParamTypeClasses
  TypeFamilies
  GADTs
  GeneralizedNewtypeDeriving
  FlexibleContexts
  EmptyDataDecls
  NoMonomorphismRestriction
  DeriveDataTypeable
  ViewPatterns
  TupleSections
  RecordWildCards
